### ISSUE TITLE
Consider adding unit tests

### ISSUE THREAD

**Issue by peter279k** [davidecesarano/Embryo-PDO#1]
- To expect classes do expected behaviors, I think it should add the unit tests.
- Once this issue is accepted, I think I can help @davidecesarano to work on this issue :).

**Comment by davidecesarano** [comment]
Hi, thank you for your proposal!

I use [phpstan](https://phpstan.org/) for my project :)

**Comment by peter279k** [comment]
Thanks for your reply.

If possible, could you add the `phpstan` command on README?

And it can be useful reference for developers.
